// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIaVtE05n3ib0A5mc-Lp9RaQ5mFNT3g4',
    appId: '1:1051381068456:web:7f6c0acaa16c6d4593889d',
    messagingSenderId: '1051381068456',
    projectId: 'socialtics-83dc2',
    authDomain: 'socialtics-83dc2.firebaseapp.com',
    databaseURL: 'https://socialtics-83dc2-default-rtdb.firebaseio.com',
    storageBucket: 'socialtics-83dc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH381pwx2KTB-qaB3Enx9a48lZ7r-Mvu8',
    appId: '1:1051381068456:android:34cd21cdcb2d439393889d',
    messagingSenderId: '1051381068456',
    projectId: 'socialtics-83dc2',
    databaseURL: 'https://socialtics-83dc2-default-rtdb.firebaseio.com',
    storageBucket: 'socialtics-83dc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkbhV9dJzBXmVRI1UcvIiCRubULnCbefo',
    appId: '1:1051381068456:ios:494aee1b0f46039793889d',
    messagingSenderId: '1051381068456',
    projectId: 'socialtics-83dc2',
    databaseURL: 'https://socialtics-83dc2-default-rtdb.firebaseio.com',
    storageBucket: 'socialtics-83dc2.appspot.com',
    iosBundleId: 'com.example.socialtics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkbhV9dJzBXmVRI1UcvIiCRubULnCbefo',
    appId: '1:1051381068456:ios:494aee1b0f46039793889d',
    messagingSenderId: '1051381068456',
    projectId: 'socialtics-83dc2',
    databaseURL: 'https://socialtics-83dc2-default-rtdb.firebaseio.com',
    storageBucket: 'socialtics-83dc2.appspot.com',
    iosBundleId: 'com.example.socialtics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfIaVtE05n3ib0A5mc-Lp9RaQ5mFNT3g4',
    appId: '1:1051381068456:web:846796ec60db6b8493889d',
    messagingSenderId: '1051381068456',
    projectId: 'socialtics-83dc2',
    authDomain: 'socialtics-83dc2.firebaseapp.com',
    databaseURL: 'https://socialtics-83dc2-default-rtdb.firebaseio.com',
    storageBucket: 'socialtics-83dc2.appspot.com',
  );
}
